export const GENERATION = {
    FETCH: "GENERATION_FETCH",
    FETCH_SUCCESS: "GENERATION_FETCH_SUCCESS",
    FETCH_ERROR: "GENERATION_FETCH_ERROR"
}

export const DRAGON = {
    FETCH: "DRAGON_FETCH",
    FETCH_SUCCESS: "DRAGON_FETCH_SUCCESS",
    FETCH_ERROR: "DRAGON_FETCH_ERROR"
}