export const FETCH_ACTION_TYPE = {
    FETCH: "FETCH",
    FETCH_SUCCESS: "FETCH_SUCCESS",
    FETCH_ERROR: "FETCH_ERROR"
};

export const GENERATION = {
    FETCH: "GENERATION_FETCH",
    FETCH_SUCCESS: "GENERATION_FETCH_SUCCESS",
    FETCH_ERROR: "GENERATION_FETCH_ERROR"
}

export const DRAGON = {
    FETCH: "DRAGON_FETCH",
    FETCH_SUCCESS: "DRAGON_FETCH_SUCCESS",
    FETCH_ERROR: "DRAGON_FETCH_ERROR"
}